site:
    title: "萌链官方博客"
    subtitle: "萌链，发现区块链的价值"
    limit: 10
    theme: theme
    lang: zh
    url: "http://blog.moechain.com"
    comment: username
    logo: "-/images/avatar.png"
    # link: "{category}/{year}/{month}/{day}/{title}.html"
    # root: "/blog"

authors:
    me:
        name: "茯苓"
        intro: "萌链作者"
        avatar: "-/images/avatar.png"

build:
    output: "public"
    # output: "public"
    port: 8000
    # Copied files to public folder when build
    copy:
        - "source/images"
    # Excuted command when use 'ink publish'
    publish: |
        git add . -A
        git commit -m "update"
        git push origin
